version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
    - 3.6.0
  - dependency-name: swoosh
    versions:
    - 1.3.0
    - 1.3.1
    - 1.3.2
    - 1.3.3
    - 1.3.4
  - dependency-name: pow
    versions:
    - 1.0.22
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
